### ISSUE TITLE
Problem compiling v0.6.1

### ISSUE THREAD

**Issue by KaroLaunonen** [royasutton/omdl#1]
Hello!

omdl looks very impressive and would be very useful for my project. However I can't compile v0.6.1 on my Fedora 27 installation.
openscad-amu has been installed successfully (as far as I understand). Here's the output from `openscad-seam -v -V`:

    openscad-seam v1.8.2

           package: openscad-amu
           version: v1.8.2
        bug report: royasutton@hotmail.com
          site url: https://royasutton.github.io/openscad-amu

        build date: Thu Jan 25 14:48:45 EET 2018
      architecture: Linux 4.14.13-300.fc27.x86_64 (x86_64)

      default lib path: /usr/local/share/openscad-amu/v1.8.2
         openscad path: /usr/bin/openscad
             bash path: /usr/bin/bash
         gnu make path: /usr/bin/make

Running `make all` stops into this:

    ########################################################################################################################
    ########################################################################################################################
    ##
    ## (begin) build/anti_prisms_db_dim.stamp
    ##
    ########################################################################################################################
    ########################################################################################################################
    OPENSCADPATH="." /usr/bin/make --makefile=build/anti_prisms_db_dim.makefile all && /usr/bin/touch  build/anti_prisms_db_dim.stamp
    make[1]: Entering directory '/home/klaunonen/Develop/omdl'
    /usr/local/share/openscad-amu/v1.8.2/include/mf/parallel_jobs.mk:37: 4 CPU's detected, configuring parallel execution --jobs=4.
    /usr/bin/time --append --verbose -o build/png/anti_prisms_db_dim_qvga_diag_decagonal_antiprism.time /usr/bin/openscad -m make -d build/png/anti_prisms_db_dim_qvga_diag_decagonal_antiprism.depend --preview --projection=o --colorscheme=Cornfield -D config=0 --viewall --autocenter --imgsize=320,240 --camera=0,0,0,55,0,25,200 -D id=\"decagonal_antiprism\" -o build/png/anti_prisms_db_dim_qvga_diag_decagonal_antiprism.png build/anti_prisms_db_dim.scad 2> build/png/anti_prisms_db_dim_qvga_diag_decagonal_antiprism.log
    make[1]: *** [build/anti_prisms_db_dim.makefile:132: build/png/anti_prisms_db_dim_qvga_diag_decagonal_antiprism.png] Error 1
    make[1]: Leaving directory '/home/klaunonen/Develop/omdl'
    make: *** [/usr/local/share/openscad-amu/v1.8.2/include/pmf/df1/scopes_rules:39: build/anti_prisms_db_dim.stamp] Error 2

Log file in `build/png/anti_prisms_db_dim_qvga_diag_decagonal_antiprism.log` says just:

    ERROR: Parser error in line 6534: syntax error

    Can't parse file 'build/anti_prisms_db_dim.scad'!

I've been stuck here as I didn't find any helpful option switches in OpenSCAD to help debug the problem.

Do you have any suggestions how to proceed?

**Comment by royasutton** [comment]
What version of openscad are you using?

RAS

**Comment by KaroLaunonen** [comment]
OpenSCAD version 2015.03-3

**Comment by KaroLaunonen** [comment]
Alright! Fetched the latest sources from Github for OpenSCAD, and now it works! Thanks!
I wonder, what is the minimum required version of OpenSCAD?

**Comment by royasutton** [comment]
Glad to here your good. Thank you for your interest and I hope the tool and lib prove useful. Other responsibilities have taken me away, but I hope to get back to developing them more soon…

Min version??? Good question… Could be identified and check/enforced… Would save some grief for sure. I’ve been hoping for a new OpenSCAD release so I can continue to ignore this question.
