### ISSUE TITLE
Undefined operation error during usage

### ISSUE THREAD

**Issue by giancarlodomanico** [royasutton/omdl#6]
I'm using the library for a very simple project but I got this warning and I do not understand why.

[WARNING: undefined operation (vector % number) in file C:/Users/Client/Documents/OpenSCAD/libraries/omdl/datatypes/identify_scalar.scad, line 168](https://github.com/royasutton/omdl/issues/168,C:/Users/Client/Documents/OpenSCAD/libraries/omdl/datatypes/identify_scalar.scad) 
[WARNING: undefined operation (vector % number) in file C:/Users/Client/Documents/OpenSCAD/libraries/omdl/datatypes/identify_scalar.scad, line 168](https://github.com/royasutton/omdl/issues/168,C:/Users/Client/Documents/OpenSCAD/libraries/omdl/datatypes/identify_scalar.scad) 
[WARNING: len() parameter could not be converted in file C:/Users/Client/Documents/OpenSCAD/libraries/omdl/datatypes/identify_scalar.scad, line 157](https://github.com/royasutton/omdl/issues/157,C:/Users/Client/Documents/OpenSCAD/libraries/omdl/datatypes/identify_scalar.scad) 
[WARNING: len() parameter could not be converted in file C:/Users/Client/Documents/OpenSCAD/libraries/omdl/datatypes/identify_scalar.scad, line 157](https://github.com/royasutton/omdl/issues/157,C:/Users/Client/Documents/OpenSCAD/libraries/omdl/datatypes/identify_scalar.scad) 
[WARNING: len() parameter could not be converted in file C:/Users/Client/Documents/OpenSCAD/libraries/omdl/math/vector_algebra.scad, line 194](https://github.com/royasutton/omdl/issues/194,C:/Users/Client/Documents/OpenSCAD/libraries/omdl/math/vector_algebra.scad) 
[WARNING: len() parameter could not be converted in file C:/Users/Client/Documents/OpenSCAD/libraries/omdl/math/vector_algebra.scad, line 194](https://github.com/royasutton/omdl/issues/194,C:/Users/Client/Documents/OpenSCAD/libraries/omdl/math/vector_algebra.scad)

This is my code for a very simple cap for a bolt

include <omdl\omdl-base.scad>;

tollerance = 0.2;
r_base = 12;
r_top = 9;
r_nut = 14.8/2+tollerance;  // 14.7 ext 12.7 in  //M8 H6.5  //S13 
h_nut = 10;
h_ext = h_nut+2;
h_wash = 1;
r_wash = r_base-1;

module rcylinder(h=1,r1=10,r2=10,vr1=1,vr2=1,center=false,$fn=128)
{
  c1 = [r1-vr1,   vr1];
  c2 = [r2-vr2, h-vr2];

  a  = 90
     + angle_ll (x_axis2d_ul, [c2, c1])
     - angle_ll (x_axis2d_ul, [distance_pp(c2, c1), vr2-vr1]);

  p1 = [0, 0];
  p2 = [r1-vr1, 0];
  p3 = c1 + vr1*[cos(a), sin(a)];
  p4 = c2 + vr2*[cos(a), sin(a)];
  p5 = [r2-vr2, h];
  p6 = [0, h];

  translate(center==true ? [0, 0, -h/2] : origin3d)
  rotate_extrude_tre ()
  union()
  {
    translate(c1)
    circle(r=vr1);

    translate(c2)
    circle(r=vr2);

    polygon
    (
      points=[p1, p2, p3, p4, p5, p6],
      paths=[[0,1,2,3,4,5]]
    );
  }
}

difference(){
   color("gray")
   translate([0,0,0.1])
   rcylinder(h=h_ext,r1=r_base,r2=r_top,vr1=0,vr2=1,center=false);

   cylinder(h=h_nut,r1=r_nut,r2=r_nut,center=false,$fn=6);
   cylinder(h=h_nut,r1=r_nut-tollerance,r2=r_nut-tollerance,center=false,$fn=30);
   cylinder(h=h_wash,r1=r_wash,r2=r_wash,center=false,$fn=30);
   
}

**Comment by royasutton** [comment]
The openscad language has changed over the past few years since this library was last updated. These warnings you see relate to the changes in the interpreted behavior of the language. Some of the assumptions made by omdl are no longer valid with current versions of openscad. I plan to address these issues soon. They are mostly related to the type identification.
